# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - bainbridgeislandteeco

on:
  push:
    branches:
      - bainbridge_island_tee_co

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{github.workspace}}/.pip
        # An explicit key for restoring and saving the cache
        key: 'python | "${{runner.os}}" | requirements.txt'
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: | 
          python | "${{runner.os}}"
          python

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bainbridgeislandteeco'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_62494261b82042a98c0710f33329e3fc }}
